version: '2.4'
services:
  # Banco
  database:
    container_name: picha-bd
    restart: unless-stopped
    image: postgres:11-alpine
    ports:
    - '2254:5432'
    expose:
      - '5432'
    volumes:
      - /data/postgres
    logging:
      driver: json-file
    environment:
      POSTGRES_DB: picha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # Picha
  picha:
    container_name: picha-backend
    restart: unless-stopped
    build:
      context: ./
      target: DEV
    ports:
      - '2200:8000'
    volumes:
      - ./:/usr/src/picha
    depends_on:
      - redis
      - database
    environment:
      TZ: America/Bahia
      DATABASE_DRIVE: django.db.backends.postgresql_psycopg2
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: picha
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      BROKER_URL: 'redis://redis:6379'
      CELERY_RESULT_BACKEND: 'redis://redis:6379'
      CELERY_TIMEZONE: 'America/Bahia'
    command: "/bin/sh -c \"celery -A picha worker -l info & \n celery -A picha beat -l info & \n python manage.py runserver 0.0.0.0:8000 \""

  redis:
    container_name: picha-redis
    restart: unless-stopped
    image: redis:3.2-alpine
    environment:
      TZ: America/Bahia
    expose:
      - '6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data: