version: '2.4'
services:  
  # Picha
  picha:
    container_name: picha-backend
    build:
      context: ./
      target: DEV
    ports:
      - '2200:8000'
    volumes:
      - ./:/usr/src/picha
    depends_on:
      - redis
    environment:
      TZ: America/Bahia
      POSTGRES_PASSWORD: postgres
      BROKER_URL: 'redis://redis:6379'
      CELERY_RESULT_BACKEND: 'redis://redis:6379'
      CELERY_TIMEZONE: 'America/Bahia'
    command: "/bin/bash -c \"celery -A picha worker -l info & \n celery -A picha beat -l info & \n python manage.py runserver 0.0.0.0:8000 \""

  redis:
    container_name: picha-redis
    image: redis:3.2-alpine
    environment:
      TZ: America/Bahia
    expose:
      - '6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data: